version: "3"
virtualmachines:
- name: host
  image: centos-cloud/centos-7
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n2-standard-2
- name: host2
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-79-post-c2r
  shell: /bin/bash
  machine_type: n1-standard-2
