version: '3'
virtualmachines:
- environment:
    TERM: xterm
  image: projects/tmm-instruqt-11-26-2021/global/images/nested-virt-9-0-20220708
  machine_type: n2-standard-2
  name: host1
  shell: /bin/bash
  allow_external_ingress:
  - http
  - https
  - high-ports