version: '3'
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-7-9-tmm-22-02-v1
  machine_type: n2-standard-2
  shell: /bin/bash
  environment:
    TERM: xterm
  #allow_external_ingress:
  #- http
  #- https
  #- high-ports