version: "3"
virtualmachines:
- name: rhel
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-redhat-tmm-20211203
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2
- name: client1
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-redhat-tmm-20211203
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2
- name: client2
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-redhat-tmm-20211203
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-2
