version: '3'
virtualmachines:
- environment:
    TERM: xterm
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-8-5-tmm-22-01-v1
  machine_type: n1-highmem-2
  name: rhel
  shell: /bin/bash
