version: "3"
virtualmachines:
- allow_external_ingress:
  - http
  - https
  - high-ports
  environment:
    TERM: xterm
  image: projects/tmm-instruqt-11-26-2021/global/images/rhel-9-0-06-13-2022-1
  name: rhel
  shell: /bin/bash
  machine_type: n1-standard-1
