version: "3"
virtualmachines:
- name: satellite
  image: tmm-instruqt-11-26-2021/satellite-04-05-22
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-4
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: rhel1
  image: tmm-instruqt-11-26-2021/rhel-8-5-03-02-2022-1
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
- name: rhel2
  image: tmm-instruqt-11-26-2021/rhel-8-5-03-02-2022-1
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
  - http
  - https
  - high-ports
