version: "3"
virtualmachines:
- name: satellite
  # image: projects/tmm-instruqt-11-26-2021/global/images/rhel-8-5-tmm-22-01-v1
  # image: projects/tmm-instruqt-11-26-2021/global/images/myee-test-image-from-snapshot
  # image: rhel-cloud/rhel-7
  # image: projects/tmm-instruqt-11-26-2021/global/images/nestedvmtest
  # image: projects/tmm-instruqt-11-26-2021/global/images/rhel-8-5-03-02-2022-1
  # image: projects/tmm-instruqt-11-26-2021/global/images/satellite-3-9-22-v1
  image: tmm-instruqt-11-26-2021/satellite-03-21-22
  shell: /bin/bash
  environment:
    TERM: xterm
  # machine_type: n1-standard-2
  # machine_type: n1-highmem-4
  machine_type: n1-standard-8
  allow_external_ingress:
    - http
    - https
    - high-ports
- name: rhel1
  image: tmm-instruqt-11-26-2021/rhel-8-5-03-02-2022-1
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
    - http
    - https
    - high-ports
- name: rhel2
  image: tmm-instruqt-11-26-2021/rhel-8-5-03-02-2022-1
  shell: /bin/bash
  environment:
    TERM: xterm
  machine_type: n1-standard-1
  allow_external_ingress:
    - http
    - https
    - high-ports