---
- name: Get available repositories
  ansible.builtin.uri:
      url: "https://localhost/katello/api/products/\
      {{ result.resources[0]['product']['id'] }}\
      /repository_sets/\
      {{ result.resources[0]['id'] }}\
      /available_repositories"
      url_username: "{{ foreman.initial_admin_username }}"
      url_password: "{{ foreman.initial_admin_password }}"
      validate_certs: false
      force_basic_auth: true
  register: available

- name: "First entry"
  when: >
      (
      available.json.results[0].substitutions.releasever is defined and
      '.' not in available.json.results[0].substitutions.releasever
      ) or
      available.json.results[0].substitutions.releasever is not defined
  ansible.builtin.set_fact:
      repo: "[ {{ available.json.results[0] }} ]"

- name: "First 3 entries"
  when: >
      (
      available.json.results[0].substitutions.releasever is defined and
      '.' in available.json.results[0].substitutions.releasever
      ) or
      available.json.results[0].substitutions.releasever is not defined
  ansible.builtin.set_fact:
      repo: "{{ available.json.results[0:3] }}"

- name: Enable Repos # noqa: args[module]
  theforeman.foreman.repository_set:
      username: "{{ foreman.initial_admin_username }}"
      password: "{{ foreman.initial_admin_password }}"
      server_url: "https://localhost"
      validate_certs: false
      organization: "{{ foreman.initial_organization }}"
      label: "{{ result.resources[0].label }}"
      repositories: "{{ repo | map('json_query', '{ basearch: substitutions.basearch, releasever:substitutions.releasever }') | list }}"
      state: enabled